using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace disconnected_ado
{
    public partial class Form1 : Form
    {
        string conStr = "Server=.\\SQLEXPRESS;Database=db_1;Integrated Security=True";

        SqlConnection con;
        SqlDataAdapter da;
        DataSet ds;
        
        public Form1()
        {
            InitializeComponent();
            con = new SqlConnection(conStr);

            da = new SqlDataAdapter("SELECT * FROM Table_2", con);

            SqlCommandBuilder cb = new SqlCommandBuilder(da);

            ds = new DataSet();

            da.Fill(ds, "Table_2");

            dataGridView1.DataSource = ds.Tables["Table_2"];
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            DataRow dr = ds.Tables["Table_2"].NewRow();

            // Don't set Id here! It will be generated by the DB.
            dr["Name"] = textName.Text;
            dr["City"] = textCity.Text;

            ds.Tables["Table_2"].Rows.Add(dr);

            da.Update(ds, "Table_2");

            // Refresh DataSet to get new Id from database
            ds.Tables["Table_2"].Clear();
            da.Fill(ds, "Table_2");

            dataGridView1.DataSource = ds.Tables["Table_2"];

            MessageBox.Show("Record Inserted with Auto-generated Id");
        }

        private void button2_Click(object sender, EventArgs e)
        {
            foreach (DataRow dr in ds.Tables["Table_2"].Rows)
            {
                if (dr["Id"].ToString() == textId.Text)
                {
                    dr["Name"] = textName.Text;
                    dr["City"] = textCity.Text;
                }
            }

            da.Update(ds, "Table_2");

            MessageBox.Show("Record Updated");
        }

        private void button3_Click(object sender, EventArgs e)
        {
            foreach (DataRow dr in ds.Tables["Table_2"].Rows)
            {
                if (dr["Id"].ToString() == textId.Text)
                {
                    dr.Delete();
                    break;
                }
            }

            da.Update(ds, "Table_2");

            MessageBox.Show("Record Deleted");
        }

        private void button4_Click(object sender, EventArgs e)
        {
            ds.Tables["Table_2"].Clear();

            da.Fill(ds, "Table_2");

            dataGridView1.DataSource = ds.Tables["Table_2"];
        }
    }
}
